# Generated by Django 3.2 on 2021-06-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210601_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_id',
            field=models.IntegerField(default=0),
        ),
    ]
