# Generated by Django 3.2 on 2021-06-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_questionanswer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserData',
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'UserData', 'verbose_name_plural': 'UserDatas'},
        ),
    ]
