# Generated by Django 3.2 on 2021-07-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_questionanswer_ans_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(unique=True),
        ),
    ]
