# Generated by Django 3.2 on 2021-07-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20210727_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('stime', models.CharField(max_length=10)),
                ('etime', models.CharField(max_length=10)),
                ('ttime', models.CharField(max_length=10)),
                ('exam_id', models.IntegerField(unique=True)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'ExamData',
                'verbose_name_plural': 'ExamDatas',
            },
        ),
    ]
