# Generated by Django 3.2 on 2021-07-31 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_examdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examdata',
            old_name='etime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='examdata',
            old_name='stime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='examdata',
            old_name='ttime',
            new_name='total_time',
        ),
    ]
