# Generated by Django 3.2 on 2021-08-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_examstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examstatus',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('started', 'Started')], default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='examstatus',
            name='time_left',
            field=models.CharField(max_length=20),
        ),
    ]
