# Generated by Django 3.2 on 2021-08-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20210802_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='ans_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('started', 'Started')], default='aamfr', max_length=10),
        ),
    ]
