# Generated by Django 3.2 on 2021-08-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_alter_questionanswer_ans_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='ans_status',
            field=models.CharField(choices=[('aamfr', 'Answered and Marked for Review'), ('ans', 'Answered and Saved')], default='aamfr', max_length=10),
        ),
    ]
