# Generated by Django 3.2 on 2021-08-12 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_alter_questionanswer_ans_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'PaperModel',
                'verbose_name_plural': 'PaperModels',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.papermodel')),
            ],
        ),
    ]
