# Generated by Django 3.2 on 2021-08-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_papermodel_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdata',
            name='type',
            field=models.CharField(default='custom-21', max_length=10),
            preserve_default=False,
        ),
    ]
