# Generated by Django 4.0 on 2022-04-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_alter_examdata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='question_id',
            field=models.IntegerField(),
        ),
    ]
