# Generated by Django 4.0 on 2022-04-11 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('answer', models.TextField()),
                ('exam_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.userdata')),
            ],
            options={
                'verbose_name': 'descanswer',
                'verbose_name_plural': 'descanswers',
            },
        ),
    ]
