# Generated by Django 4.0 on 2022-04-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_descanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papermodel',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
