# Generated by Django 4.0 on 2022-04-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_alter_papermodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdata',
            name='type',
            field=models.CharField(default='custom-21', max_length=100),
        ),
    ]
