# Generated by Django 4.0 on 2022-04-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_alter_examdata_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='descanswer',
            name='ans_status',
            field=models.CharField(choices=[('aamfr', 'Answered and Marked for Review'), ('ans', 'Answered and Saved')], default='aamfr', max_length=10),
        ),
    ]
