# Generated by Django 4.0 on 2022-04-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0029_result_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='descanswer',
            name='marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descanswer',
            name='max_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
