# Generated by Django 4.0 on 2022-04-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0030_descanswer_marks_descanswer_max_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescResultStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('status', models.CharField(choices=[('corrected', 'Corrected'), ('started', 'Started')], default='started', max_length=20)),
            ],
            options={
                'verbose_name': 'descresultstatus',
                'verbose_name_plural': 'descresultstatuses',
            },
        ),
    ]
