# Generated by Django 4.0 on 2022-04-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0031_descresultstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('exam_id', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('attempted', models.IntegerField()),
                ('unattempted', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name': 'DescResult',
                'verbose_name_plural': 'DescResults',
            },
        ),
    ]
