# Generated by Django 4.0 on 2022-04-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0033_alter_descanswer_ans_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descanswer',
            name='ans_status',
            field=models.CharField(choices=[('na', 'Not Answered'), ('aamfr', 'Answered and Marked for Review'), ('ans', 'Answered and Saved')], default='na', max_length=10),
        ),
    ]
