# Generated by Django 4.0.4 on 2022-07-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0034_alter_descanswer_ans_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descanswer',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
