# Generated by Django 4.0.4 on 2022-07-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0035_alter_descanswer_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descanswer',
            name='max_marks',
            field=models.IntegerField(default=0),
        ),
    ]
