# Generated by Django 4.0.4 on 2022-07-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0036_alter_descanswer_max_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='descanswer',
            name='user_id',
            field=models.IntegerField(default=191030001),
            preserve_default=False,
        ),
    ]
